refactor: Use build presets

diff --git a/libexec/swiftenv-build b/libexec/swiftenv-build
--- a/libexec/swiftenv-build
+++ b/libexec/swiftenv-build
@@ -55,13 +55,20 @@ build_swift() {
   echo "Building Swift"
   echo "This may take a very long time..."
 
-  ./utils/build-script -R -- --install-prefix="$destination" >&4 2>&1
-  cd "$TMP"
-}
+  case $(uname) in
+  'Darwin' )
+    preset=swiftenv_macOS
+    ;;
+  'Linux' )
+    preset=swiftenv_linux
+    ;;
+  * )
+    preset=swiftenv
+    ;;
+  esac
 
-install_swift() {
-  mkdir -p "$destination/usr/bin"
-  cp "$TMP/build/Ninja-ReleaseAssert/"swift-*/bin/swift{,-demangle} "$destination/usr/bin"
+  ./utils/build-script --preset-file=$PACKAGE_BUILD_PRESET --preset=$preset install_destdir="$destination" >&4 2>&1
+  cd "$TMP"
 }
 
 build_failed() {
@@ -74,7 +81,7 @@ build_failed() {
 }
 
 list_definitions() {
-  ls "$SWIFTENV_SOURCE_PATH/share/swiftenv-build" | sort_versions | uniq
+  ls -pL "$SWIFTENV_SOURCE_PATH/share/swiftenv-build" | grep -v / | sort_versions | uniq
 }
 
 sort_versions() {
@@ -128,6 +135,12 @@ if ! [ -r "$PACKAGE_DEFINITION" ]; then
   exit 1
 fi
 
+PACKAGE_BUILD_PRESET="$SWIFTENV_SOURCE_PATH/share/swiftenv-build/presets/$package.ini"
+if ! [ -r "$PACKAGE_BUILD_PRESET" ]; then
+  echo "Package build preset not found for $package"
+  exit 1
+fi
+
 # Swift build takes up a lot of room and unfortunately
 # had issues where I've ran out of space in /tmp while building
 TMP="$SWIFTENV_ROOT/tmp/swiftenv-build-$package"
@@ -148,7 +161,6 @@ fi
 mkdir -p "$destination"
 trap build_failed ERR
 source "$PACKAGE_DEFINITION"
-install_swift
 
 if $clean; then
   rm -fr $TMP
