Add support for more Linux versions
Stop asking swiftenv-api.fuller.li for file name when it is easy
to construct

diff --git a/libexec/swiftenv-install b/libexec/swiftenv-install
--- a/libexec/swiftenv-install
+++ b/libexec/swiftenv-install
@@ -35,6 +35,10 @@ update_version_files() {
   fi
 }
 
+get_os_version_variable() {
+  grep "^$1=" /etc/os-release | cut -d "=" -f2 | tr -d '"'
+}
+
 get_platform() {
   if [ -n "$SWIFTENV_PLATFORM" ]; then
     echo "$SWIFTENV_PLATFORM"
@@ -48,18 +52,21 @@ get_platform() {
 
   case $(uname) in
   'Linux' )
-    if command -v "lsb_release" >/dev/null 2>&1; then
-      if [ $(lsb_release -is) = "Ubuntu" ]; then
-        echo "ubuntu$(lsb_release -rs)"
-      elif [ $(lsb_release -ius) = "Ubuntu" ]; then
-        echo "ubuntu$(lsb_release -rus)"
-      else
-        echo "unsupported-platform"
-      fi
-    elif [ -r "/etc/lsb-release" ]; then
-      echo "The `lsb_release` command line tool is missing. `/etc/lsb-release` file is found."
-      exit 1
-    fi
+    OS_NAME=$(get_os_version_variable NAME)	  
+    OS_VERSION_ID=$(get_os_version_variable VERSION_ID)
+    echo "$OS_NAME:$OS_VERSION_ID"
+    #if command -v "lsb_release" >/dev/null 2>&1; then
+    #  if [ $(lsb_release -is) = "Ubuntu" ]; then
+    #    echo "ubuntu$(lsb_release -rs)"
+    #  elif [ $(lsb_release -ius) = "Ubuntu" ]; then
+    #    echo "ubuntu$(lsb_release -rus)"
+    #  else
+    #    echo "unsupported-platform"
+    #  fi
+    #elif [ -r "/etc/lsb-release" ]; then
+    #  echo "The `lsb_release` command line tool is missing. `/etc/lsb-release` file is found."
+    #  exit 1
+    #fi
     ;;
   'Darwin' )
     echo "osx"
@@ -96,8 +103,13 @@ download() {
   local FILE
   URL=$1
   FILE=$2
-
+  
   if ! [ -r "$FILE" ]; then
+    status_code=$(curl -I -s -o /dev/null -w "%{http_code}" $URL || true)
+    if [ "$status_code" != "200" ]; then
+      echo "Cannot find file $URL"
+      exit 1
+    fi  
     curl -C - -Lo "$FILE.download" "$URL"
     mv "$FILE.download" "$FILE"
   fi
@@ -193,21 +205,56 @@ build_version() {
 }
 
 find_binary_url_from_api() {
-  vlog "Checking for a URL for the $VERSION on $(get_platform)."
+  echo "Checking for a URL for Swift $VERSION on $(get_platform)."
 
-  status_code=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://swiftenv-api.fuller.li/versions/$VERSION/binaries/$(get_platform)" || true)
+  case $(get_platform) in
+    'Ubuntu:16.04' )
+      SWIFT_BUILD_FOLDER="ubuntu1604"
+      SWIFT_ZIP_FILE="ubuntu16.04"
+      ;;
+    'Ubuntu:18.04' )
+      SWIFT_BUILD_FOLDER="ubuntu1804"
+      SWIFT_ZIP_FILE="ubuntu18.04"
+      ;;
+    'Ubuntu:20.04' )
+      SWIFT_BUILD_FOLDER="ubuntu2004"
+      SWIFT_ZIP_FILE="ubuntu20.04"
+      ;;
+    'CentOS Linux:7')
+      SWIFT_BUILD_FOLDER="centos7"
+      SWIFT_ZIP_FILE="centos7"
+      ;;
+    'CentOS Linux:8')
+      SWIFT_BUILD_FOLDER="centos8"
+      SWIFT_ZIP_FILE="centos8"
+      ;;
+    'Amazon Linux:2')
+      SWIFT_BUILD_FOLDER="amazonlinux2"
+      SWIFT_ZIP_FILE="amazonlinux2"
+      ;;
+    'osx')
+      url="https://swift.org/builds/swift-$VERSION-release/xcode/swift-$VERSION-RELEASE/swift-$VERSION-RELEASE-osx.pkg"
+      return
+    *)
+      echo "There was a problem identifying your OS $(get_platform)"
+      exit 1  
+  esac
 
-  if [ "$status_code" = "404" ]; then
-    vlog "Did not find a binary release for $VERSION on $(get_platform)."
-  elif [ "$status_code" = "200" ]; then
-    url="$(curl --silent https://swiftenv-api.fuller.li/versions/$VERSION/binaries/$(get_platform) -H 'Accept: text/plain')"
-  elif [ "$status_code" = "000" ]; then
-    echo "There was a problem checking for a binary release of $VERSION, could not connect to the swiftenv API."
-    exit 1
-  else
-    echo "There was a problem checking for a binary release of $VERSION, server returned $status_code."
-    exit 1
-  fi
+  url="https://swift.org/builds/swift-$VERSION-release/$SWIFT_BUILD_FOLDER/swift-$VERSION-RELEASE/swift-$VERSION-RELEASE-$SWIFT_ZIP_FILE.tar.gz"
+
+  #status_code=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://swiftenv-api.fuller.li/versions/$VERSION/binaries/$(get_platform)" || true)
+#
+#  if [ "$status_code" = "404" ]; then
+#    vlog "Did not find a binary release for $VERSION on $(get_platform)."
+#  elif [ "$status_code" = "200" ]; then
+#    url="$(curl --silent https://swiftenv-api.fuller.li/versions/$VERSION/binaries/$(get_platform) -H 'Accept: text/plain')"
+#  elif [ "$status_code" = "000" ]; then
+#    echo "There was a problem checking for a binary release of $VERSION, could not connect to the swiftenv API."
+#    exit 1
+#  else
+#    echo "There was a problem checking for a binary release of $VERSION, server returned $status_code."
+#    exit 1
+#  fi
 }
 
 sort_versions() {
@@ -385,7 +432,7 @@ if ([ "$build" == "auto" ] || [ "$build" == "false" ]); then
   fi
 
   if [ "$url" ]; then
-    vlog "Installing $VERSION from $url on $(get_platform)."
+    echo "Installing $VERSION from $url on $(get_platform)."
     install_binary "$VERSION" "$url"
   elif [ "$build" == "false" ]; then
     echo "Could not find a binary release of $VERSION."
